config/routes.rb
Rails.application.routes.draw do

  root to: 'search#index'

  resources :ranks
  resources :types, only: [:index, :create, :update, :edit, :destroy]
  resources :risks, only: [:index, :create, :update, :edit, :destroy]

  resources :search, only: :index do
    collection do
      get :autocomplete_type_code
      get :autocomplete_type_description
      get :autocomplete_risk_code
      get :autocomplete_risk_description
    end

  end

end

app/models/rank.rb
class Rank
  include Mongoid::Document
  include Mongoid::Timestamps

  field :code,        type: String
  field :description, type: String
  field :libelle,     type: String

  has_and_belongs_to_many :types
  has_and_belongs_to_many :risks

  before_save do |this|
    this.libelle =  "#{this.code} - #{this.description}"
  end

end

app/models/risk.rb
class Risk
  include Mongoid::Document
  include Mongoid::Timestamps
  field :code,          type: String
  field :description,   type: String
  field :libelle,       type: String

  has_and_belongs_to_many :ranks

  validates_uniqueness_of :code
  validates_presence_of   :code, :description

  before_save do |this|
    this.libelle =  "#{this.code} - #{this.description}"
  end

end

app/models/type.rb
class Type
  include Mongoid::Document
  include Mongoid::Timestamps
  field :code,          type: String
  field :description,   type: String
  field :libelle,       type: String

  validates_uniqueness_of :code
  validates_presence_of   :code, :description

  has_and_belongs_to_many :ranks

  before_save do |this|
    this.libelle =  "#{this.code} - #{this.description}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  http_basic_authenticate_with :name => "bou", :password => 'bou'

  def index

  end
end

app/controllers/ranks_controller.rb
class RanksController < ApplicationController
  before_action :set_rank, only: [:show, :edit, :update, :destroy]

  def index
    @ranks = Rank.all
    if params[:risk_ids]
      @ranks = @ranks.all_in(risk_ids: params[:risk_ids])
    end
    if params[:type_ids]
      @ranks = @ranks.all_in(type_ids: params[:type_ids])
    end
  end

  def show
  end

  def new
    @rank = Rank.new
  end

  def edit
  end

  def create
    @rank = Rank.new(rank_params)

    if @rank.save
      flash[:success] = 'Le rang a bien été créé'
      redirect_to ranks_path
    else
      flash[:danger] = "Une erreur est survenue: #{@rank.errors.full_messages}"
      render :new
    end
  end

  def update
    if @rank.update(rank_params)
      flash[:success] = 'Le rang a bien été mis à jour'
      redirect_to ranks_path
    else
      flash[:danger] = "Une erreur est survenue: #{@rank.errors.full_messages}"
      render :edit
    end
  end

  def destroy
    @rank.destroy
    flash[:success] = 'Le rang a bien été supprimé'
    redirect_to ranks_url
  end

  private
    def set_rank
      @rank = Rank.find(params[:id])
    end

    def rank_params
      params.require(:rank).permit(:code, :description, :libelle, :type_ids => [], :risk_ids => [])
    end
end

app/controllers/risks_controller.rb
class RisksController < ApplicationController
  before_action :set_risk, only: [:edit, :update, :destroy]

  def index
    @risks = Risk.all
  end

  def edit

  end

  def create
    @risk = Risk.new(risk_params)

    respond_to do |format|
      if @risk.save
        format.js
      else
        format.js { render :create_error}
      end
    end
  end

  def update
    if @risk.update(risk_params)
      flash[:success] = 'Le risque a bien été mis à jour'
      redirect_to risks_path and return
    else
      flash[:danger] = "Une erreur est survenue: #{@risk.errors.full_messages}"
      render :edit
    end
  end

  def destroy
    @risk.destroy
    flash[:success] = 'Le risque a bien été supprimé'
    redirect_to risks_url
  end

  private
    def set_risk
      @risk = Risk.find(params[:id])
    end

    def risk_params
      params.require(:risk).permit(:code, :description, :libelle)
    end
end

app/controllers/search_controller.rb
class  SearchController < ApplicationController
  autocomplete :type, :code,        full: true, display_value: :libelle
  autocomplete :type, :description, full: true, display_value: :libelle
  autocomplete :risk, :code,        full: true, display_value: :libelle
  autocomplete :risk, :description, full: true, display_value: :libelle

  def index
    @risk = Risk.new
    @type = Type.new

  end
end

app/controllers/types_controller.rb
class TypesController < ApplicationController
  before_action :set_type, only: [:edit, :update, :destroy]

  def index
    @types = Type.all
  end

  def edit

  end

  def create
    @type = Type.new(type_params)

    respond_to do |format|
      if @type.save
        format.js
      else
        format.js { render :create_error}
      end
    end
  end

  def update
    if @type.update(type_params)
      flash[:success] = 'Le type de risque a bien été mis à jour'
      redirect_to types_path and return
    else
      flash[:danger] = "Une erreur est survenue: #{@type.errors.full_messages}"
      render :edit
    end
  end

  def destroy
    @type.destroy
    flash[:success] = 'Le type de risque a bien été supprimé'
    redirect_to types_url
  end

  private
    def set_type
      @type = Type.find(params[:id])
    end

    def type_params
      params.require(:type).permit(:code, :description, :libelle)
    end
end

app/helpers/application_helper.rb
module  ApplicationHelper

#   def nav_link(name, href = nil, options = {}, html_options = {}, &block)
#     if current_page?(href.nil? ? name : href)
#       "<li class='active'>#{link_to(name, href, options, &block)}</li>".html_safe
#     else
#       "<li>#{link_to(name, href, options, &block)}</li>".html_safe
#     end
#   end

#   def form_group(attribute, label = attribute.to_s, options = {}, &block)
#     raw "<div class='form-group #{options['form-group-class']}'><label for='#{attribute}'>#{label}</label>" + capture(&block) + "</div>"
#   end

  def bo_box(title, options = {}, &block)
    options = {color: 'info'}.merge(options)
    raw %Q"<div id='#{options[:id]}' class='box box-#{options[:color]} #{options[:class]}'>
            <div class='box-header-#{options[:color]}'>
              <h4>#{title}</h4>
            </div>
            <div class='box-content'>
              #{capture(&block)}
              <div class='clearfix'></div>
            </div>
          </div>"
  end

#   def panel(title, options = {}, &block)
#     options = {color: 'info'}.merge(options)

#     raw %Q"<div class='#{options[:class]}'>
#             <div class='panel panel-#{options[:color]}'>
#               <div class='panel-heading'>
#                 <h3 class='panel-title'>#{title}</h3>
#               </div>
#               <div class='panel-body'>
#                 #{capture(&block)}
#               </div>
#             </div>
#           </div>"
#   end

#   def control_group(attribute, label = "", options = {}, &block)

#     raw  %Q{<div class='form-group #{options[:class]}' id="options[:id]">
#               <label class='control-label col-sm-3 col-lg-height col-middle' for='#{attribute}'>
#                 #{label}
#                 <small>#{options[:small]}</small>
#               </label>
#               <div class='col-sm-9 col-lg-height col-middle'>
#                 #{capture(&block)}
#               </div>
#               <div class='clearfix'></div>
#             </div>}
#   end

#   def panel_group(options, &block)
#     raise 'You must provide an :id to your panel_group' if options[:id].blank?

#     raw %Q{
#       <div class="panel-group #{options[:class]}" id="#{options[:id]}">
#         #{capture(&block)}
#       </div>
#     }
#   end

#   def panel_collapse(title, options={}, &block )
#     raise 'You must provide a :panel_group_id to your panel_collapse' if options[:panel_group_id].blank?

#     options = { color: 'info', href: SecureRandom.hex }.merge(options)

#     raw %Q{
#       <div class="panel panel-#{options[:color]} #{options[:class]}" id="#{options[:id]}">
#         <div class="panel-heading">
#           <h4 class="panel-title">
#             #{options[:title]}
#             <a data-toggle="collapse" data-parent="##{options[:panel_group_id]}" href="##{options[:href]}">
#               #{title}
#             </a>
#           </h4>
#         </div>
#         <div id="#{options[:href]}" class="panel-collapse collapse">
#           <div class="panel-body">
#             #{capture(&block)}
#           </div>
#         </div>
#       </div>
#     }

#   end


end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class='alert alert-<%= name %>'>
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Risks</title>
    <meta name="description" content="Risks n'est pas un jeu">
    <meta name="author" content="Antoine Mary">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <!-- Header -->
    <div id="top-nav" class="navbar navbar-inverse navbar-static-top">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="icon-toggle"></span>
        </button>
        <ul class="nav navbar-nav">
            <li><a href="<%= root_path %>">Recherche</a></li>
            <li><a href="<%= types_path %>">Types de riques</a></li>
            <li><a href="<%= risks_path %>">Risques</a></li>
            <li><a href="<%= ranks_path %>">Classements</a></li>
          </ul>
      </div>
    </div>
    <div class="container">
      <div class="row">
        <div id="messages" class='col-sm-12'>
        </div>
      </div>
      <div class="row">
        <div id="messages">

        </div>
        <div class="col-sm-12">
          <%= render 'layouts/messages' %>
          <%= yield %>
        </div>
      </div>
    <div>
    <div class="clearfix"></div>
    <footer>
    </footer>
  </body>
</html>

app/views/ranks/_form.html.erb
<%= form_for @rank, layout: :basic do |f| %>

    <%= f.text_field :code %>

    <%= f.text_field :description %>

    <%= f.select :type_ids, Type.all.map {|t| [t.description, t._id.to_s]}, {label: 'Types de risque <small>(choix multiple)</small>'.html_safe}, multiple: true %>

    <%= f.select :risk_ids, Risk.all.map {|t| [t.description, t._id.to_s]}, {label: 'Risques <small>(choix multiple)</small>'.html_safe}, multiple: true %>

    <%= f.submit 'Valider' %>

<% end %>

app/views/ranks/edit.html.erb
<h1>Editing rank</h1>

<%= render 'form' %>

<%= link_to 'Back', ranks_path %>

app/views/ranks/index.html.erb
<h1>Classemnts</h1>

<table class='table table-bordered table-hover'>
  <thead>
    <tr>
      <th>Code</th>
      <th>Description</th>
      <th>Types de risque</th>
      <th>Risques</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @ranks.each do |rank| %>
      <tr>
        <td><%= rank.code %></td>
        <td><%= rank.description %></td>
        <td><%= rank.types.map(&:description)*' - ' %></td>
        <td><%= rank.risks.map(&:description)*' - ' %></td>
        <td>
          <%= link_to 'Éditer', edit_rank_path(rank), class: 'btn btn-info' %>
          <%= link_to 'Supprimer', rank, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Créer un nouveau rang', new_rank_path %>

app/views/ranks/new.html.erb
<h1>New rank</h1>

<%= render 'form' %>

<%= link_to 'Back', ranks_path %>

app/views/ranks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Code:</strong>
  <%= @rank.code %>
</p>

<p>
  <strong>Description:</strong>
  <%= @rank.description %>
</p>

<%= link_to 'Edit', edit_rank_path(@rank) %> |
<%= link_to 'Back', ranks_path %>

app/views/risks/_form.html.erb
<%= form_for @risk, layout: :basic do |f| %>

    <%= f.text_field :code %>

    <%= f.text_field :description %>


    <%= f.submit 'Valider' %>

<% end %>

app/views/risks/create.js.erb
$('#messages').html("<div class='alert alert-info alert-dismissible' role='alert'><button type='button' class='close' data-dismiss='alert'><span aria-hidden='true'>&times;</span><span class='sr-only'>Close</span></button><strong>Yep</strong> <%= @risk.libelle %> a bien été créé</div>");

app/views/risks/create_error.js.erb
$('#messages').html("<div class='alert alert-danger alert-dismissible' role='alert'><button type='button' class='close' data-dismiss='alert'><span aria-hidden='true'>&times;</span><span class='sr-only'>Close</span></button><strong>Meh</strong> Erreur à la création: <%= @risk.errors.full_messages %></div>");

app/views/risks/edit.html.erb
<h1>Editer un risque</h1>

<%= render 'form' %>

<%= link_to 'Back', risks_path %>

app/views/risks/index.html.erb
<h1>Risques</h1>

<table class='table table-bordered table-hover'>
  <thead>
    <tr>
      <th>Code</th>
      <th>Description</th>
      <th>Classements</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @risks.each do |risk| %>
      <tr>
        <td><%= risk.code %></td>
        <td><%= risk.description %></td>
        <td><%= risk.ranks.map(&:description)*' - ' %></td>
        <td>
          <%= link_to 'Éditer', edit_risk_path(risk), class: 'btn btn-info' %>
          <%= link_to 'Supprimer', risk, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/search/index.html.erb
<%= bo_box 'Chercher des types de risques', color: 'info' do  %>
  <div class="col-sm-6">
    <%= form_for Type.new, remote: true, layout: :inline do |f| %>
      <%= f.autocomplete_field  :code,
                                autocomplete_type_code_search_index_path,
                                class: 'form-control',
                                placeholder: 'Code' %>
      <%= f.autocomplete_field  :description,
                                autocomplete_type_description_search_index_path,
                                class: 'form-control',
                                placeholder: 'Description' %>
      <%= f.submit 'Créer', class: 'form-control' %>
    <% end -%>
  </div>
  <div class="col-sm-6" id='found-type'>

  </div>
<% end -%>

<%= bo_box 'Chercher des risques', color: 'info' do  %>
  <div class="col-sm-6">
    <%= form_for Risk.new, remote: true, layout: :inline do |f| %>
      <%= f.autocomplete_field  :code,
                                autocomplete_risk_code_search_index_path,
                                class: 'form-control',
                                placeholder: 'Code' %>
      <%= f.autocomplete_field  :description,
                                autocomplete_risk_description_search_index_path,
                                class: 'form-control',
                                placeholder: 'Description' %>
      <%= f.submit 'Créer', class: 'form-control' %>
    <% end -%>
  </div>
  <div class="col-sm-6" id='found-risk'>

  </div>
<% end -%>

<div class="box box-danger ">
  <div class="box-header-danger">
    <h4>Classements</h4>
  </div>
  <div class="box-content">
    <div id="results">

    </div>
    <div class="clearfix"></div>
  </div>
</div>

<script type='text/javascript'>

  var search =  {
    riskIds:  [],
    typeIds:  [],
    updateResults: function () {
      var str = '';
      if ( (this.riskIds.length > 0) || (this.typeIds.length > 0)){
        var parameters = $.param({risk_ids: this.riskIds, type_ids: this.typeIds });
        $.ajax({
          url:      '<%= ranks_path %>?' + parameters,
          method:   'GET',
          dataType: 'JSON'
        }).done(function (data) {
          data.forEach(function (rank) {
            str += "<div class='alert alert-danger' role='alert'>" + rank.libelle + " <a style='float:right' href='/ranks/" + rank.id.$oid +"/edit' >éditer</a></div>"
          });
          $("#results").html(str);
        });
      } else {
        $("#results").html(str);
      }
    },
    initEvents: function () {
      ['type', 'risk'].forEach(function (klass) {

        ['code', 'description'].forEach(function (att) {
          $('#' + klass + '_' + att).bind('railsAutocomplete.select', function(event, data){
            $(this).val(null);
            search[klass + 'Ids'].push(data.item.id);
            $('#found-' + klass).append(
              "<div class='alert alert-info alert-dismissible'" + "data-id='" + data.item.id + "' role='alert'><button type='button' class='close' data-dismiss='alert'><span aria-hidden='true'>&times;</span><span class='sr-only'>Close</span></button><strong>" + data.item.value + "</strong></div>");

            search.updateResults();
            $('.alert[data-id="' + data.item.id + '"]').bind('closed.bs.alert', function (event) {
              var i = search[klass + 'Ids'].indexOf($(this).attr('data-id'));
              search[klass + 'Ids'].splice(i, 1);
              search.updateResults();
            });
          });
        });
      });
    }
  };
  search.initEvents();


</script>

app/views/types/_form.html.erb
<%= form_for @type, layout: :basic do |f| %>

    <%= f.text_field :code %>

    <%= f.text_field :description %>

    <%= f.submit 'Valider' %>

<% end %>

app/views/types/create.js.erb
$('#messages').html("<div class='alert alert-info alert-dismissible' role='alert'><button type='button' class='close' data-dismiss='alert'><span aria-hidden='true'>&times;</span><span class='sr-only'>Close</span></button><strong>Yep</strong> <%= @type.libelle %> a bien été créé</div>");

app/views/types/create_error.js.erb
$('#messages').html("<div class='alert alert-danger alert-dismissible' role='alert'><button type='button' class='close' data-dismiss='alert'><span aria-hidden='true'>&times;</span><span class='sr-only'>Close</span></button><strong>Meh</strong> Erreur à la création: <%= @type.errors.full_messages %></div>");

app/views/types/edit.html.erb
<h1>Éditer un type de risque</h1>

<%= render 'form' %>

<%= link_to 'Back', types_path %>

app/views/types/index.html.erb
<h1>Types de risque</h1>

<table class='table table-bordered table-hover'>
  <thead>
    <tr>
      <th>Code</th>
      <th>Description</th>
      <th>Classements</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @types.each do |type| %>
      <tr>
        <td><%= type.code %></td>
        <td><%= type.description %></td>
        <td><%= type.ranks.map(&:description)*' - ' %></td>
        <td>
          <%= link_to 'Éditer', edit_type_path(type), class: 'btn btn-info' %>
          <%= link_to 'Supprimer', type, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>